//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option or rebuild the Visual Studio project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Web.Application.StronglyTypedResourceProxyBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Language {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Language() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Resources.Language", global::System.Reflection.Assembly.Load("App_GlobalResources"));
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Access token was incorrect..
        /// </summary>
        internal static string GetFolderFailure {
            get {
                return ResourceManager.GetString("GetFolderFailure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to List of folders was returned successfully..
        /// </summary>
        internal static string GetFolderSuccess {
            get {
                return ResourceManager.GetString("GetFolderSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sign in failed. One of the credentials was incorrect..
        /// </summary>
        internal static string SignInFailure {
            get {
                return ResourceManager.GetString("SignInFailure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sign in was successful.
        /// </summary>
        internal static string SignInSuccess {
            get {
                return ResourceManager.GetString("SignInSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File upload failed..
        /// </summary>
        internal static string UploadFileFailure {
            get {
                return ResourceManager.GetString("UploadFileFailure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File(s) uploaded successfully..
        /// </summary>
        internal static string UploadFileSuccess {
            get {
                return ResourceManager.GetString("UploadFileSuccess", resourceCulture);
            }
        }
    }
}
